layout_spectrum: 0.48946520453318954
typography_spectrum: 0.11296174093149602
color:
  brandStrength: 0.8181707747280598
  lightness: 0.4740939778275788
  saturation: 0.07818441325798631
  rhythmicContrast: 0.5495390321593732
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
name: JAW DROPPERS
navigation:
  - name: About me
    url: 'http://stevepharris.com/'
    type: external
title: CAUSE WHO DOESN'T LIKE HOT CHICKS??
description: Testing The Grid AI
