typography_spectrum: 0.037362183909863234
color:
  brandStrength: 0.7237228660378605
  lightness: 0.4854593896307051
  saturation: 0.01358218933455646
  rhythmicContrast: 0.9867793712764978
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.8717143225949258
name: JAW DROPPERS
navigation:
  - name: About me
    url: 'http://stevepharris.com/'
    type: external
title: CAUSE WHO DOESN'T LIKE HOT CHICKS??
description: Testing The Grid AI
